server:
  http_listen_port: 3200


distributor:
  receivers:
    zipkin:
      endpoint: 0.0.0.0:9411 
      

querier:
  frontend_worker:
    frontend_address: 127.0.0.1:9095    

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks