global:
  scrape_interval: 5s

rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: "api-cargafila-job"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          application: "api-cargafila"