server:
  port: 8080

spring:
  jpa:
    open-in-view: true
  application:
    name: cargaFilaApplication
  profiles:
    active:
      - test

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    zipkin:
      tracing:
        endpoint: http://localhost:9411/api/v2/spans
