name: Feature CI

on:
  push:
    branches:
      - 'feature/*'

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    outputs:
      branch_name: ${{ steps.extract_branch.outputs.branch_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/main.api/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build application
        working-directory: ./backend
        run: mvn clean package -DskipTests -Dmaven.compiler.showWarnings=false

      - name: Extract Branch Name
        id: extract_branch
        run: echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

  pull_request:
    name: Create Pull Request to Develop
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git config --global url."https://".insteadOf "ssh://"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.TOKEN }}
          commit-message: 'Build successful - creating PR'
          title: 'PR from ${{ needs.build.outputs.branch_name }}'
          body: 'Auto-generated PR after successful build of ${{ needs.build.outputs.branch_name }}'
          base: develop
          branch: ${{ needs.build.outputs.branch_name }}
      
      
